package dependency

object Dependency {
    val kotlin_standard_library = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Version.kotlin}"
    val kotlin_reflect = "org.jetbrains.kotlin:kotlin-reflect:${Version.kotlin}"
    val ktx = "androidx.core:core-ktx:${Version.ktx}"
    val kotlin_coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.coroutines_version}"
    val kotlin_coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.coroutines_version}"
    val kotlin_coroutines_play_services = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Version.coroutines_play_services}"
    val dagger = "com.google.dagger:dagger:${Version.dagger}"
    val navigation_fragment = "androidx.navigation:navigation-fragment-ktx:${Version.nav_components}"
    val navigation_runtime = "androidx.navigation:navigation-runtime:${Version.nav_components}"
    val navigation_ui = "androidx.navigation:navigation-ui-ktx:${Version.nav_components}"
    val navigation_dynamic = "androidx.navigation:navigation-dynamic-features-fragment:${Version.nav_components}"
    val material_dialogs = "com.afollestad.material-dialogs:core:${Version.material_dialogs}"
    val material_dialogs_input = "com.afollestad.material-dialogs:input:${Version.material_dialogs}"
    val room_runtime = "androidx.room:room-runtime:${Version.room}"
    val room_ktx = "androidx.room:room-ktx:${Version.room}"
    val play_core = "com.google.android.play:core:${Version.play_core}"
    val leak_canary = "com.squareup.leakcanary:leakcanary-android:${Version.leak_canary}"
    val firebase_firestore = "com.google.firebase:firebase-firestore-ktx:${Version.firebase_firestore}"
    val firebase_auth = "com.google.firebase:firebase-auth:${Version.firebase_auth}"
    val firebase_analytics = "com.google.firebase:firebase-analytics-ktx:${Version.firebase_analytics}"
    val firebase_crashlytics = "com.google.firebase:firebase-crashlytics:${Version.firebase_crashlytics}"

    val firebase_bom = "com.google.firebase:firebase-bom:${Version.firebase_bom_ver}"
    val firebase_firestore_bom = "com.google.firebase:firebase-firestore-ktx"
    val firebase_auth_bom = "com.google.firebase:firebase-auth"
    val firebase_analytics_bom = "com.google.firebase:firebase-analytics-ktx"
    val firebase_crashlytics_bom = "com.google.firebase:firebase-crashlytics"

    val lifecycle_runtime = "androidx.lifecycle:lifecycle-runtime:${Version.lifecycle_version}"
    val lifecycle_coroutines = "androidx.lifecycle:lifecycle-livedata-ktx:${Version.lifecycle_version}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Version.retrofit2_version}"
    val gson_retrofit = "com.squareup.retrofit2:converter-gson:${Version.retrofit2_version}"
    val markdown_processor = "com.yydcdut:markdown-processor:${Version.markdown_processor}"
    val gson_google = "com.google.code.gson:gson:${Version.gson_google_version}"
}