package dependency

object Version {
    val gradle = "4.2.1"
    val compilesdk = 30
    val minsdk = 21
    val targetsdk = 30
    val kotlin = "1.5.20"
    val ktx = "1.6.0"
    val dagger = "2.25.4"
    val nav_components = "2.3.5"
    val material_dialogs = "3.3.0"
    val room = "2.3.0"
    val appcompat = "1.3.0"
    val constraintlayout = "2.0.4"
    val material_design = "1.3.0"
    val play_core = "1.10.0"
    val play_services = "4.3.8"
    val leak_canary = "2.7"
    val swipe_refresh_layout = "1.1.0"
    val firebase_firestore = "23.0.1"
    val firebase_analytics = "19.0.0"
    val firebase_crashlytics = "18.1.0"
    val firebase_auth = "21.0.1"
    val espresso_core = "3.4.0"
    val espresso_idling_resource = "3.4.0"
    val mockk_version = "1.11.0"
    val test_runner = "1.3.0"
    val test_core = "1.3.2"
    val coroutines_version = "1.5.0"
    val coroutines_play_services = "1.5.0"
    val lifecycle_version = "2.4.0-alpha02"
    val retrofit2_version = "2.9.0"
    val markdown_processor = "0.1.3"
    val junit_jupiter_version = "5.7.2"
    val junit_4_version = "4.13.2"
    val fragment_version = "1.3.5"
    val androidx_test_ext = "1.1.3"
    val crashlytics_gradle = "2.7.1"
    val mannodermaus_junit5 = "1.7.1.1"
}